# This fuzzes.

name: Fuzz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"
  RUST_MIN_STACK: 8000000

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
# TODO/FIXME: fix date types.
#        run: [byte, date, float, int, run, str, time, toa, unsigned, up]
        run: [byte, float, int, run, str, time, toa, unsigned, up]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install
      run: |
        rustup default nightly
        cargo install cargo-fuzz

    - name: Fuzz
      run: cargo +nightly fuzz run -O ${{ matrix.run }} -- -max_total_time=300
